### ISSUE TITLE
jellyseerr反复重启

### ISSUE THREAD

**Issue by LL66001** [LuckyPuppy514/automatic-theater#20]
[error]: TypeError: Cannot read properties of undefined (reading 'schedule')

    at startJobs (/app/dist/job/schedule.js:66:64)

    at /app/dist/index.js:121:34 

 ELIFECYCLE  Command failed with exit code 1.

**Comment by Scallions** [comment]
切到1.9版本可以正常运行

**Comment by blueemp** [comment]
更换jellyseerr版本到develop解决了
2024-11-06T07:53:14.730Z [info]: Starting Overseerr version 2.0.1 
2024-11-06T07:53:15.402Z [info][Notifications]: Registered notification agents 
2024-11-06T07:53:15.410Z [error]: TypeError: Cannot read properties of undefined (reading 'schedule')
    at startJobs (/app/dist/job/schedule.js:66:64)
    at /app/dist/index.js:121:34 
2024-11-06T07:58:20.688Z [info]: Commit Tag: cf59102ef91fa0e907cc6369b0fe60b503c823ca 
2024-11-06T07:58:22.566Z [info]: Starting Overseerr version develop-cf59102ef91fa0e907cc6369b0fe60b503c823ca 
2024-11-06T07:58:24.087Z [info][Notifications]: Registered notification agents 
2024-11-06T07:58:24.179Z [info][Jobs]: Scheduled jobs loaded 
2024-11-06T07:58:24.581Z [info][Server]: Server ready on port 5055

**Comment by shijingyu** [comment]
同样问题，更改配置文件，更换到develop版本解决
